value1 = int(input("Please Enter your 1st Value as an INTEGER: "))
print("your 1th value's type is {} ".format(type(value1)))
value2 = str(input("Please Enter your 2nd Value as a WORD: "))
print("your 2nd value's type is {} ".format(type(value2)))
value3 = float(input("Please Enter 3th Value as a DECIMAL NUMBER: "))
print("your 3th value's type is {} ".format(type(value3)))
value4 = int(input("Please Enter your 4th Value as an INTEGER: "))
print("your 4th value's type is {} ".format(type(value4)))
value5 = str(input("Please Enter your 5th Value as a WORD: "))
print("your 5th value's type is {} ".format(type(value5)))
print("Values that you've entred are ({}, {}, {}, {}, {})".format(value1,value2,value3,value4,value5))